// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/joke.ts";
import * as $2 from "./routes/favorite.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/love.tsx";
import * as $5 from "./routes/meet.tsx";
import * as $$0 from "./islands/Meet.tsx";
import * as $$1 from "./islands/favorite.tsx";
import * as $$2 from "./islands/love.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/joke.ts": $1,
    "./routes/favorite.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/love.tsx": $4,
    "./routes/meet.tsx": $5,
  },
  islands: {
    "./islands/Meet.tsx": $$0,
    "./islands/favorite.tsx": $$1,
    "./islands/love.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
